const SPOTIFY_TOKENS = 'SPOTIFY_TOKENS';
const SPOTIFY_ME_BEGIN = 'SPOTIFY_ME_BEGIN';
const SPOTIFY_ME_SUCCESS = 'SPOTIFY_ME_SUCCESS';
const SPOTIFY_ME_FAILURE = 'SPOTIFY_ME_FAILURE';

module.exports = {
	SPOTIFY_TOKENS,
	SPOTIFY_ME_BEGIN,
	SPOTIFY_ME_SUCCESS,
	SPOTIFY_ME_FAILURE
}